"""Pass 3: Lock & Gate Structure — creates progression gates on exits.

This pass reads the room graph and world concept, then asks the LLM to
place locks on exits to create a structured progression experience.
Locks transform a free-roaming room graph into a game with pacing,
gating, and earned access.

## FK Constraint Strategy

The ``locks`` table has a foreign key ``key_item_id REFERENCES items(id)``.
However, actual items are not created until Pass 4 (Items). To avoid FK
violations when ``PRAGMA foreign_keys=ON``:

1. We insert locks with ``key_item_id = NULL`` for all lock types
   (including ``key``-type locks).
2. The ``key_item_id`` placeholder name generated by the LLM is stored
   in the pipeline context under ``lock_key_mapping`` so the Items pass
   can: (a) create the item with that exact ID, and (b) update the lock
   row to set ``key_item_id`` to the now-existing item.
3. This two-phase approach keeps FK integrity intact and avoids dummy
   rows.

The Items pass (Pass 4) is responsible for calling:
    UPDATE locks SET key_item_id = ? WHERE id = ?
after inserting each key item.
"""

from __future__ import annotations

import json
import logging
from collections import deque

from anyzork.db.schema import GameDB
from anyzork.generator.providers.base import BaseProvider, GenerationContext

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# JSON schema the LLM must conform to
# ---------------------------------------------------------------------------

LOCKS_SCHEMA: dict = {
    "type": "object",
    "required": ["locks"],
    "properties": {
        "locks": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "lock_type",
                    "target_exit_id",
                    "locked_message",
                    "unlock_message",
                ],
                "properties": {
                    "id": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9_]*$",
                        "description": "Unique snake_case lock ID.",
                    },
                    "lock_type": {
                        "type": "string",
                        "enum": ["key", "puzzle", "combination", "state", "npc"],
                        "description": "The kind of lock.",
                    },
                    "target_exit_id": {
                        "type": "string",
                        "description": (
                            "The exit ID this lock gates. Must match an "
                            "exit from the room graph."
                        ),
                    },
                    "key_item_id": {
                        "type": ["string", "null"],
                        "description": (
                            "For key-type locks: the snake_case ID of the "
                            "item that will unlock this. This item does not "
                            "exist yet — the Items pass will create it. "
                            "Use a descriptive name like 'rusty_key' or "
                            "'security_keycard'. NULL for non-key locks."
                        ),
                    },
                    "key_location_room_id": {
                        "type": ["string", "null"],
                        "description": (
                            "For key-type locks: the room ID where the key "
                            "item should be placed. Must be reachable WITHOUT "
                            "passing through this lock. NULL for non-key locks."
                        ),
                    },
                    "locked_message": {
                        "type": "string",
                        "description": (
                            "What the player sees when they try to pass "
                            "while locked. Should hint at the solution type."
                        ),
                    },
                    "unlock_message": {
                        "type": "string",
                        "description": (
                            "What the player sees when the lock opens."
                        ),
                    },
                    "consume_key": {
                        "type": "boolean",
                        "description": (
                            "Whether using the key destroys it. Only "
                            "relevant for key-type locks. Default false."
                        ),
                    },
                },
                "additionalProperties": False,
            },
        },
    },
    "additionalProperties": False,
}

# ---------------------------------------------------------------------------
# Scale-based lock count guidance
# ---------------------------------------------------------------------------

_LOCK_RANGES: dict[str, tuple[int, int]] = {
    "small":  (1, 2),
    "medium": (3, 5),
    "large":  (6, 10),
}

# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------

_PROMPT = """\
You are a progression designer for a text adventure game engine called AnyZork.

You are executing **Pass 3: Lock & Gate Structure**. Your job is to place \
locks on exits to create a structured progression experience with pacing, \
gating, and a sense of earned access.

## World Concept

```json
{concept_json}
```

## Room Graph (from Pass 2)

### Rooms
```json
{rooms_json}
```

### Exits
```json
{exits_json}
```

### Start Room: `{start_room_id}`

## Your Task

Create **{lock_count_min} to {lock_count_max} locks** on exits to gate \
progression through the world.

## Lock Types

- **key**: Requires a specific inventory item. You define the item's ID \
(it will be created in the next pass). The item MUST be placed in a room \
reachable WITHOUT passing through this lock.
- **puzzle**: Solved by completing an in-room puzzle (wired in a later pass). \
Set `key_item_id` to null.
- **combination**: Requires inputting a code the player discovers via lore. \
Set `key_item_id` to null.
- **state**: Requires game state flags to be set. Set `key_item_id` to null.
- **npc**: Requires an NPC interaction. Set `key_item_id` to null.

For this pass, focus primarily on **key** locks — they are the most \
straightforward and reliable gating mechanism. Use 1-2 other types if \
they fit the theme well.

## Critical Constraint: Key-Gate Reachability

This is the most important rule in the entire generation pipeline:

**For every key-type lock, the key item MUST be reachable by the player \
BEFORE they encounter the lock.** "Reachable" means the player can get to \
the room containing the key WITHOUT passing through this locked exit or \
any other locked exit whose key is also inaccessible.

For each key lock you create, you MUST verify:
1. Which room the key is in (`key_location_room_id`)
2. That a path exists from the start room to that key room that does NOT \
pass through this lock's target exit
3. That no circular dependencies exist (lock A's key is behind lock B, \
and lock B's key is behind lock A)

If you place multiple locks, they must be solvable in SOME valid order. \
Think of it as a topological sort — there must be at least one sequence \
in which the player can collect keys and unlock doors without getting \
stuck.

## Progression Design Guidelines

1. **At least one lock on the critical path.** Without progression gating, \
there is no game — just a walking tour.

2. **Lock density increases with depth.** Early areas feel open and \
welcoming. Later areas feel earned and gated.

3. **Breathing room between locks.** After unlocking a gate, the player \
should get at least one new room to explore freely before hitting the \
next gate.

4. **Region boundaries are natural lock points.** The transition between \
regions is a perfect place for a locked door or gate.

5. **No softlocks.** The player must never reach a state where the game \
cannot be completed:
   - No key behind the lock it opens (circular dependency)
   - No consumable key that can be used on the wrong lock
   - No one-way exit that strands the player without a required key

6. **Locked messages hint at solutions.** "The iron door is locked. A \
keyhole glints beside it." tells the player to find a key. "A magical \
barrier hums with energy" tells them to look for a magical solution.

## Output Format

Return a single JSON object matching this schema:

```json
{schema_json}
```

For key-type locks, always provide both `key_item_id` (the item name to \
be created) and `key_location_room_id` (where to place it).

Produce ONLY the JSON object. No commentary, no markdown fences.
"""


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

class LockValidationError(ValueError):
    """Raised when the lock structure fails validation."""


def _validate(
    data: dict,
    concept: dict,
    rooms: list[dict],
    exits_list: list[dict],
) -> None:
    """Validate lock structure for integrity and key-gate reachability."""
    errors: list[str] = []

    locks = data.get("locks", [])
    room_ids = {r["id"] for r in rooms}
    exit_ids = {e["id"] for e in exits_list}

    # Lock count within expected range
    scale = concept.get("scale", "medium")
    lock_min, lock_max = _LOCK_RANGES.get(scale, (1, 10))
    if not (lock_min <= len(locks) <= lock_max):
        # Allow some tolerance — warn but do not hard-fail for +-1
        if len(locks) == 0:
            errors.append("No locks generated. At least one is required.")
        elif abs(len(locks) - lock_min) > 2 and abs(len(locks) - lock_max) > 2:
            errors.append(
                f"Lock count ({len(locks)}) is outside expected range "
                f"({lock_min}-{lock_max}) for scale '{scale}'."
            )

    # Check each lock
    seen_lock_ids: set[str] = set()
    for lock in locks:
        lid = lock.get("id", "<missing>")

        # Duplicate IDs
        if lid in seen_lock_ids:
            errors.append(f"Duplicate lock ID: '{lid}'.")
        seen_lock_ids.add(lid)

        # Target exit must exist
        target_exit = lock.get("target_exit_id", "")
        if target_exit not in exit_ids:
            errors.append(
                f"Lock '{lid}' targets unknown exit '{target_exit}'."
            )

        # Key-type checks
        if lock.get("lock_type") == "key":
            key_item = lock.get("key_item_id")
            key_room = lock.get("key_location_room_id")

            if not key_item:
                errors.append(
                    f"Key-type lock '{lid}' has no key_item_id."
                )
            if not key_room:
                errors.append(
                    f"Key-type lock '{lid}' has no key_location_room_id."
                )
            elif key_room not in room_ids:
                errors.append(
                    f"Key-type lock '{lid}' places key in unknown room "
                    f"'{key_room}'."
                )

        # Required fields
        if not lock.get("locked_message"):
            errors.append(f"Lock '{lid}' has no locked_message.")
        if not lock.get("unlock_message"):
            errors.append(f"Lock '{lid}' has no unlock_message.")

    # --- Key-gate reachability check ---
    # Build adjacency from exits, excluding locked exits
    # For each key-type lock, verify the key room is reachable from start
    # without passing through that lock's exit
    if not errors:
        _validate_reachability(locks, rooms, exits_list, errors)

    if errors:
        raise LockValidationError(
            "Lock validation failed:\n  - " + "\n  - ".join(errors)
        )


def _validate_reachability(
    locks: list[dict],
    rooms: list[dict],
    exits_list: list[dict],
    errors: list[str],
) -> None:
    """Check that every key-type lock's key is reachable without that lock."""
    room_ids = {r["id"] for r in rooms}
    start_rooms = [r for r in rooms if r.get("is_start")]
    if not start_rooms:
        return  # Can't check without a start room
    start_id = start_rooms[0]["id"]

    # For each key-type lock, BFS from start excluding that lock's exit
    key_locks = [lock for lock in locks if lock.get("lock_type") == "key"]

    for lock in key_locks:
        target_exit_id = lock.get("target_exit_id", "")
        key_room = lock.get("key_location_room_id", "")

        if not key_room or key_room not in room_ids:
            continue  # Already caught above

        # Build adjacency excluding the locked exit (and any exit with
        # the same from->to pair in either direction, since the reverse
        # might also be blocked by this lock)
        # Find the exit to get from/to room info
        locked_exit_info = None
        for ex in exits_list:
            if ex["id"] == target_exit_id:
                locked_exit_info = ex
                break

        blocked_pairs: set[tuple[str, str]] = set()
        if locked_exit_info:
            blocked_pairs.add(
                (locked_exit_info["from_room_id"], locked_exit_info["to_room_id"])
            )

        adjacency: dict[str, set[str]] = {rid: set() for rid in room_ids}
        for ex in exits_list:
            pair = (ex["from_room_id"], ex["to_room_id"])
            if pair not in blocked_pairs:
                adjacency[ex["from_room_id"]].add(ex["to_room_id"])

        # BFS from start
        visited: set[str] = set()
        queue: deque[str] = deque([start_id])
        while queue:
            current = queue.popleft()
            if current in visited:
                continue
            visited.add(current)
            for neighbor in adjacency.get(current, set()):
                if neighbor not in visited:
                    queue.append(neighbor)

        if key_room not in visited:
            errors.append(
                f"Key-gate violation: lock '{lock['id']}' requires key "
                f"'{lock.get('key_item_id')}' in room '{key_room}', but "
                f"that room is not reachable from start without passing "
                f"through the locked exit '{target_exit_id}'."
            )


# ---------------------------------------------------------------------------
# Pass entry point
# ---------------------------------------------------------------------------

def run_pass(db: GameDB, provider: BaseProvider, context: dict) -> dict:
    """Run Pass 3: Lock & Gate Structure.

    Reads the concept and room graph from ``context``, asks the LLM to
    generate lock placements, validates key-gate reachability, inserts
    locks into the DB (with ``key_item_id=NULL`` to avoid FK violations),
    marks locked exits, and returns the updated context.

    The ``context["lock_key_mapping"]`` dict maps lock_id -> {key_item_id,
    key_location_room_id} so that the Items pass can create the key items
    and backfill the FK.

    Args:
        db: The GameDB instance.
        provider: The LLM provider to call.
        context: Pipeline context dict with ``"concept"``, ``"rooms"``,
                 ``"exits"``, and ``"start_room_id"``.

    Returns:
        Updated context with ``"locks"`` and ``"lock_key_mapping"`` added.

    Raises:
        LockValidationError: If the lock structure fails validation.
    """
    concept: dict = context["concept"]
    rooms: list[dict] = context["rooms"]
    exits_list: list[dict] = context["exits"]
    start_room_id: str = context["start_room_id"]

    # Determine lock count range from scale
    scale = concept.get("scale", "medium")
    lock_min, lock_max = _LOCK_RANGES.get(scale, (1, 10))

    # Simplify room data for the prompt (just id, name, region)
    rooms_summary = [
        {"id": r["id"], "name": r["name"], "region": r["region"]}
        for r in rooms
    ]

    # Simplify exit data for the prompt
    exits_summary = [
        {
            "id": e["id"],
            "from_room_id": e["from_room_id"],
            "to_room_id": e["to_room_id"],
            "direction": e["direction"],
        }
        for e in exits_list
    ]

    # Build the prompt
    prompt = _PROMPT.format(
        concept_json=json.dumps(concept, indent=2),
        rooms_json=json.dumps(rooms_summary, indent=2),
        exits_json=json.dumps(exits_summary, indent=2),
        start_room_id=start_room_id,
        lock_count_min=lock_min,
        lock_count_max=lock_max,
        schema_json=json.dumps(LOCKS_SCHEMA, indent=2),
    )

    # Build generation context
    gen_ctx = GenerationContext(
        existing_data={
            "concept": concept,
            "rooms": rooms_summary,
            "exits": exits_summary,
        },
        seed=context.get("seed"),
        temperature=0.7,
        max_tokens=8_192,
    )

    # Call the LLM
    data: dict = provider.generate_structured(
        prompt=prompt,
        schema=LOCKS_SCHEMA,
        context=gen_ctx,
    )

    # Validate
    _validate(data, concept, rooms, exits_list)

    # --- Insert locks into DB and mark exits as locked ---
    locks = data["locks"]
    lock_key_mapping: dict[str, dict] = {}
    exit_ids = {e["id"] for e in exits_list}

    for lock in locks:
        # --- Validate target_exit_id (NOT NULL FK) ---
        target_exit = lock.get("target_exit_id", "")
        if target_exit not in exit_ids:
            logger.warning(
                "Lock %s references non-existent target_exit_id %r — "
                "skipping lock",
                lock.get("id", "<unknown>"),
                target_exit,
            )
            continue

        # Build the insert fields.  key_item_id is set to NULL to
        # avoid FK violation — the Items pass will backfill it.
        fields: dict = {
            "id": lock["id"],
            "lock_type": lock["lock_type"],
            "target_exit_id": lock["target_exit_id"],
            "locked_message": lock["locked_message"],
            "unlock_message": lock["unlock_message"],
            "is_locked": 1,
            "consume_key": int(lock.get("consume_key", False)),
        }

        # key_item_id is always NULL at this stage; we store the
        # intended key info in the context for the Items pass.
        if lock.get("lock_type") == "key" and lock.get("key_item_id"):
            lock_key_mapping[lock["id"]] = {
                "key_item_id": lock["key_item_id"],
                "key_location_room_id": lock.get("key_location_room_id"),
            }

        db.insert_lock(**fields)

        # Mark the target exit as locked in the exits table
        db.lock_exit(lock["target_exit_id"])

    # --- Return pass-specific data ---
    return {
        "locks": locks,
        "lock_key_mapping": lock_key_mapping,
    }
